### ISSUE TITLE
Provide a way to run the frontend without npm installed on windows

### ISSUE THREAD

**Issue by geowarin** [geowarin/boot-react#10]
The gradle node plugin will automatically install the correct version of npm to build the project.
However, we still require users to install their own version of node/npm to run the frontend in dev mode.

I will keep an eye of the node wrapper discussed [here](https://github.com/srs/gradle-node-plugin/issues/24), looks promising.

**Comment by geowarin** [comment]
I added a wrapper script for npm (UNIX only).
Tell me if it helps.

I'm looking for a volunteer for a windows version :smile:

**Comment by kucharzyk** [comment]
My wrapper scripts looks like that:

nodew.cmd (windows)
```
@echo off
setlocal
set NODE_EXE=""
for /r %%x in (*node.exe) do set NODE_EXE=%%x
set NODE_HOME=%NODE_EXE:node.exe=%
set PATH=%NODE_HOME%;%PATH%
if not exist %NODE_EXE% (
  echo Node not found! Run gradle build first!
) else (
  %NODE_EXE% %*
)
@echo on
```

yarn.cmd (windows)
```
@echo off
setlocal
set YARN_SCRIPT=%~dp0build\yarn\node_modules\yarn\bin\yarn.js
if not exist %YARN_SCRIPT% (
  echo Node not found! Run gradle build first!
) else (
  nodew.cmd %YARN_SCRIPT% %*
)
@echo on
```

nodew (linux)
```
@echo off
setlocal
set YARN_SCRIPT=%~dp0build\yarn\node_modules\yarn\bin\yarn.js
if not exist %YARN_SCRIPT% (
  echo Node not found! Run gradle build first!
) else (
  nodew.cmd %YARN_SCRIPT% %*
)
@echo on
```

yarnw (linux)
```
#!/usr/bin/env bash

YARN_SCRIPT="./build/yarn/node_modules/yarn/bin/yarn.js"

if [ ! -f $YARN_SCRIPT ]; then
    echo "Yarn not found! Run gradle build first!"
else
    ./nodew $YARN_SCRIPT "$@"
fi
```

**Comment by geowarin** [comment]
Fixed by [automatically running yarn](https://github.com/geowarin/boot-react/blob/master/backend/src/main/java/react/dev/YarnRunner.java) in development
