### ISSUE TITLE
Static Assets (for example: Images)

### ISSUE THREAD

**Issue by nullsumme** [geowarin/boot-react#16]
Hey,

Thanks a lot for this great "starter" application. Since I'm very new to all of this I have a small quastion:
What do we need to add so we can access static files like images?

**Comment by nullsumme** [comment]
Okay, looks like for development we can use something like this:
> app.use('/images', express.static(__dirname + '/assets/images'));

**Comment by geowarin** [comment]
The best way IMHO is to use the URL loader of webpack.
I pushed [a branch](https://github.com/geowarin/boot-react/blob/add-logo/frontend/webpack.config.js#L54) demoing that.

This way, you will have all your assets passed through webpack. You can do many types of optimizations from here.

With your method, keep in mind that you will also have to figure out a way to put the images in the public directory of the application's jar in prod. It can be as simple as simply put them here in the first place.

**Comment by nullsumme** [comment]
Thanks for the reply.
With this way I can access the files via webpack, thats fine. But what can I do if i need the image for some CSS stuff like 'background: url()?

**Comment by geowarin** [comment]
This should automatically work: see [the section about urls](https://github.com/webpack/css-loader#usage) of the css loader.

**Comment by nullsumme** [comment]
Perfect! You are right, it works just like that. 
Thanks a lot.
