### ISSUE TITLE
Preparing the frontend for npm distribution

### ISSUE THREAD

**Issue by ddewaele** [geowarin/boot-react#19]
Great repo .... love how it demonstrates a lot of stuff (react / spring boot / hot reloading / redux / ....)

I had a question on the software distribution part of the frontend code using npm.

Imagine at some point you want to wrap the frontend in an npm package and publish it to the npm registry (to do your webapp software distribution using npm)

When doing an ```npm pack```, you can generate a tarball that would correspond to the tarball that would get uploaded to the npm repo when doing an ```npm publish```

~~By default, npm publish will publish all files unless you specify a ```files``` property in your ```package.json```, but it will also include all your package.json ```dependencies```.~~

~~This will result in the following :~~

```
MacBook-Pro-3:frontend ddewaele$ npm pack
boot-react-frontend-0.0.1.tgz
MacBook-Pro-3:frontend ddewaele$ tar -tvf boot-react-frontend-0.0.1.tgz 
-rw-r--r--  0 501    20       1907 Feb 27 23:21 package/package.json
-rw-r--r--  0 501    20     376032 Feb 27 22:59 package/dist/bundle.js
-rw-r--r--  0 501    20    3256598 Feb 27 22:59 package/dist/bundle.js.map
-rw-r--r--  0 501    20        184 Feb 27 22:59 package/dist/index.html
-rw-r--r--  0 501    20      13087 Feb 27 22:59 package/dist/styles.css
-rw-r--r--  0 501    20         87 Feb 27 22:59 package/dist/styles.css.map
-rw-r--r--  0 501    20       3880 Feb 27 22:49 package/node_modules/history/package.json
-rw-r--r--  0 501    20       3154 Dec  7 20:47 package/node_modules/history/README.md
-rw-r--r--  0 501    20        673 Feb  4 19:35 package/node_modules/history/es6/Actions.js
-rw-r--r--  0 501    20       4790 Feb  4 19:35 package/node_modules/history/es6/createBrowserHistory.js
-rw-r--r--  0 501    20        918 Feb  4 19:35 package/node_modules/history/es6/createDOMHistory.js
-rw-r--r--  0 501    20       6864 Feb  4 19:35 package/node_modules/history/es6/createHashHistory.js
-rw-r--r--  0 501    20       7695 Feb  4 19:35 package/node_modules/history/es6/createHistory.js
-rw-r--r--  0 501    20        985 Feb  4 19:35 package/node_modules/history/es6/PathUtils.js
-rw-r--r--  0 501    20       3819 Feb  4 19:35 package/node_modules/history/es6/createMemoryHistory.js
-rw-r--r--  0 501    20        271 Feb  4 19:35 package/node_modules/history/es6/deprecate.js
-rw-r--r--  0 501    20        209 Feb  4 19:35 package/node_modules/history/es6/enableBeforeUnload.js
-rw-r--r--  0 501    20        184 Feb  4 19:35 package/node_modules/history/es6/enableQueries.js
-rw-r--r--  0 501    20       1139 Feb  4 19:35 package/node_modules/history/es6/index.js
-rw-r--r--  0 501    20        139 Feb  4 19:35 package/node_modules/history/es6/ExecutionEnvironment.js
-rw-r--r--  0 501    20        537 Feb  4 19:35 package/node_modules/history/es6/runTransitionHook.js
-rw-r--r--  0 501    20       2132 Feb  4 19:35 package/node_modules/history/es6/DOMUtils.js
-rw-r--r--  0 501    20       4161 Feb  4 19:35 package/node_modules/history/es6/useBasename.js
-rw-r--r--  0 501    20       1908 Feb  4 19:35 package/node_modules/history/es6/DOMStateStorage.js
....
```

~~As you can see it packages up the dist folder (the "binary" part of the webapp that you in fact want to distribute), but it also packages all the node modules. (your dependencies)~~

When doing an ```npm install -g``` of your webapp, npm will pull in all of its dependencies, and as these dependencies have already been included in the dist bundle.js by webpack, that didn't seem to make much sense that npm would need to pull them in again during an ```npm install -g```.

I had some discussions about this with some colleagues, and the only solution (or workaround) I see is to declare all dependencies as devDependencies. (Node will not install devDependencies when installing a node package).

At this point you don't really need these node modules anymore (as you are distributing a webapp that has already been webpacked). You simply need to distribute your dist folder.

What is your idea on that ?

**Comment by geowarin** [comment]
Hi @ddewaele!

In [the npm docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) it says:

> Additionally, everything in node_modules is ignored, except for bundled dependencies.

It seems that `history` is the only lib that ends up in the tar folder. Maybe it's a bug with `react-router`?
Or a bug with npm... Have you tried with npm 2?
You could also try to put the package in `.npmignore` but it looks like you are not supposed to do that.

Or you could totally put everything as a devDependency anyway, webpack puts everything you need in the bundle so the difference between dependencies and dev-dependencies is only semantic (what is required for the build and the tests vs what is required at runtime).

Honestly, I'm having a hard time figuring out your use case. :persevere:
Isn't npm used to distribute sources ? You can then use the package.json to rebuild the module.
For binary distributions, I'd use S3 or a CDN.

Could you tell me more about this, I'd be curious to know your thinking :smile:

**Comment by ddewaele** [comment]
You're right about it only being ```history```.  I wasn't clear on this.  What I'm struggling with is the fact if you ever decide to ```npm publish``` an npm package that contains a webapp, people that will ```npm install``` it will pull in all the dependencies. If all people want to do is run your (webpacked) webapp, they don't need all these dependences getting pulled in (for the semantic reason you're describing).

I guess my feeling is that npm shouldn't be limited to distributing sources only. I think it can also be used to distribute runtime code. (like a (webpacked) webapp). As we're seeing more and more frontend stuff being pushed to npm, it kinda felt natural to use npm as a distribution mechanism for this.

Much like maven / gradle pushes compiled java code into a maven repo, I feel like npm can be used to push webpacked webapps into an npms repo.

For example, we're using ```npm publish``` to publish our webpacked webapp to the npmjs repo as a private package. It makes it very easy to ```npm install / update``` the webapp on dev/staging/prod servers. The tarball simply contains the webpacked webapp. Distributing the "source" version of the webapp doesn't make a lot of sense in his case. 

The source is only important for the developers working on it, and we use git as a distribution mechanism for the code.
Seeing the webapp sources as a dependency to another node module is also not applicable here, as the webapp is just a top-level module that will never be included as a dependency for another module.

I agree the difference between dependencies and dev-dependencies is semantic.

**Comment by geowarin** [comment]
Today, there seems to be a real difference between the way libraries and web applications are being built with webpack and distributed with npm.

The author of a library will face different topologies of users: those who consume ES5 code, those who will compile ES6 code (to take advantage of tree shaking) and those who want to consume the library from a CDN for example (UMD builds).

So all of those outputs will be included in the npm package. Most of the time, the package will also contain sources for developer convenience.

For good examples see [this generator](https://github.com/JedWatson/generator-react-component), [nwb](https://github.com/insin/nwb) or [this config](https://github.com/webpack/webpack/tree/master/examples/multi-part-library).

----

This project isn't a library so no particular care has been taken for the reuse of this code in a different context. As you said, it would be difficult to see a web application as a module anyway.

It looks to me that using npm to distribute a web application is a simplistic use case. In the end you just want a tarball, a version number and an update system.
You don’t need the build system, the dependencies system or any other facilities provided by npm.

Even if I kind of like your idea of using npm to do that, I would not keep doing it if the system gets in my way.
If it forces you to change your dependencies for no obvious reason, for instance.

In that case, I would just switch to a simple custom system.
It is simple to make your CI system detect a new tag in your repo and make it build a zip of your dist folder.

Using S3, bintray or even [github releases](https://docs.travis-ci.com/user/deployment/releases/) you can store some binaries easily.

If your question is: can npm be used as a repository for binaries? I would answer, “maybe” even though it does not strike me as being its primary purpose.
I guess you would be better off opening an issue on npm’s repo for suggestions or ideas !

It is unclear to me what direction npm will take with the arrival of "compiled" source code on its platform.
In maven for instance, there is support for sources and documentation. It is clear what a successful, reusable package will look like.

In npm, I think this is an open question, a lot of repositories like react-router have faced the question of the libraries formats it would support.
As you can see, the ES6 build has some interesting side effects :laughing:

**Comment by ddewaele** [comment]
I've seen people doing both extremes.

- doing the distribution manually (running webpack locally on their laptop and then manually copying files over to production servers)
- doing all kinds of custom scripting 

In the javascript space, there seems to be a tendency towards simplification and giving npm more and more responsibility.

You're correct in saying that you simply want a tarbal, a version number and an update system, but the way I saw it :

- The tarbal is provided by package.json / ```npm publish```.
- The version number is provided by ```npm version```.
- The update system is provided by npm itself (```npm update```)
- The release mechanism (scm tagging / tarbal versioning) is provided by npm (```npm version``` / ```npm publish```)
- The secure repo (even for private modules) is provided by the npm registry
- If the target system doesn't have npm , the tarbal can be downloaded securely over http (npm registry)

So this looked to me like an ideal fit and I didn't feel the need to bring in another mechanism for releasing the software. Its kinda like how maven / gradle works. You use the build tool to build / version / release your code and upload your artifacts (compiled and packaged java code) to a repository. The maven repository can contain re-usable JAR files, but also top-level artifacts like WAR files / EAR files that will never be re-used. 

Just wanted to hear your take on this....

**Comment by geowarin** [comment]
You make some very good points.
I've never used npm that way but I agree that it looks like a valid use case :beer: 

I hope that you can get to the bottom of why history is included in the `npm pack` then!

**Comment by ddewaele** [comment]
I think that's just a bug somewhere ... Curious to find out where npm will position itself in the upcoming months / years ....

Thanks for the discussion. I'm giving a talk tomorrow on JS dev workflow & release mgmt and I'll be using your repo and doing some live coding on it ....  Not a big expert on Gradle so your repo was really helpful to see how to integrate node/npm with it.  Will include a link in the presentation to your github repo.

**Comment by geowarin** [comment]
That's great to hear! Good luck for your presentation, then.

**Comment by ddewaele** [comment]
@geowarin Talk went well ... slides are here if you're interested : http://slides.com/davydewaele/react-dev-workflow-release-mgmt#/

**Comment by geowarin** [comment]
Thanks @ddewaele! Great talk, very interesting. Thanks for sharing
