### ISSUE TITLE
gradle stop,but nodejs not stop

### ISSUE THREAD

**Issue by notreami** [geowarin/boot-react#22]
gradle stop,but nodejs not stop, Only  pkill -9 node

**Comment by geowarin** [comment]
Yes, that's unfortunately a know issue with the node plugin.
My recommandation is to start the frontend server from the command line with npm.

I wrote a little script (npmw) which let you use the node version downloaded by gradle on unix systems (mac, linux).
If you are on windows and would like to contribute a npmw.bat, I would be really interested.
