### ISSUE TITLE
Add support to server rendering

### ISSUE THREAD

**Issue by douglascorrea** [geowarin/boot-react#23]
@geowarin good work in this starter kit! Thanks!

I would like to suggest to add server rendering to improve SEO and first load.

One good reference is this article: http://winterbe.com/posts/2015/02/16/isomorphic-react-webapps-on-the-jvm/

**Comment by geowarin** [comment]
Hello douglas,

Thanks for your kind words. Yes, I know this article, very good read!
Server side rendering would be a great addition to this project.

Unfortunately, making this work and keeping the hot reload working is a big endeavour.
I don't have the time to work on it right now but I'll gladly accept any PR.

If you have the time to get something going, we could definitely work on it together.

**Comment by geowarin** [comment]
I think SSR is beyond the scope of this project.
