### ISSUE TITLE
Cannot find module "../../../assets/stylus/main.styl

### ISSUE THREAD

**Issue by kamalhasanqc** [geowarin/boot-react#28]
Hello geowarin,
First of all I really appreciate your work. I am having a java script exception running your project ie: "Error: Cannot find module "../../../assets/stylus/main.styl". I saw that you have hard coded this string to show with exception. Can you help me resolve the problem. Your dicst/main.js is showing in a single line I cant figure out the issue.
Thanks

**Comment by kanderson450** [comment]
@kamalhasanqc See Pull Request #29 on how to resolve this issue.

**Comment by geowarin** [comment]
Fixed in #29, thanks to @kanderson450

**Comment by kamalhasanqc** [comment]
Thanks
