### ISSUE TITLE
Serving proper 404s from the backend for non-existing pages

### ISSUE THREAD

**Issue by pulse00** [geowarin/boot-react#43]
I'm wondering how others handle proper 404 status responses from the backend. With the current setup, the [SinglePageAppConfig](https://github.com/geowarin/boot-react/blob/master/backend/src/main/java/react/config/SinglePageAppConfig.java) simply returns the index.html with an http status of 200 for each url.

My current idea is to duplicate the route configuration and whitelist all available routes in this class and return 404 for everything else, but this is error prone. 

How are others handling this scenario?

**Comment by geowarin** [comment]
What about handling this with react-router ?

```js
import React from 'react';
import { Route, IndexRoute, Redirect } from 'react-router';

export default (onLogout) => (
  <Route path="/" name="app" component={App}>
    <IndexRoute component={SimpleListComponent}/>
    <Route path="private" component={privateRoute(PrivatePage)}/>
    <Route path="login" component={LoginPage}/>
    <Route path="logout" onEnter={onLogout}/>
    <Route path='/404' component={NotFoundPage} />
    <Redirect from='*' to='/404' />
  </Route>
);
```

We are currently following (kinda, I hope) the recommendations from [react-router's doc](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server).
I'm afraid you can't have the 404 status with client -only routing.

An alternative would be handling routing on the server side. That's what we do on my current project.
It basically involves writing you own router (it's as bad as it sounds) but maybe it would be more in line with what you want to do?

**Comment by pulse00** [comment]
> An alternative would be handling routing on the server side. That's what we do on my current project.

yeah, that's what we're thinking about. I was assuming there's no real better option, but just in case i though i'd ask.

thanks for the info.
